apiVersion: kustomize.config.k8s.io/v1beta1
kind: KustomizationPatch

vars:
  - name: NAMESPACE
    objref:
      apiVersion: apps/v1
      kind: Deployment
      name: app
    fieldref:
      fieldpath: metadata.namespace

configurations:
  - kustomize-configuration.yaml