apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
spec:
  rules:
  - host: app.$(NAMESPACE).tld
    http:
      paths:
      - path: 
        backend:
          serviceName: app
          servicePort: http
