# https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/#canary-deployments
# https://medium.com/google-cloud/kubernetes-canary-deployments-for-mere-mortals-13728ce032fe
# https://dev.to/mostlyjason/intro-to-deployment-strategies-blue-green-canary-and-more-3a3
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

replicas:
  - name: app-canary
    count: 1

patches:
  - patch: |-
      # Need to change the deployment name so that the original app deployment still runs (with the old version)
      - op: replace
        path: /metadata/name
        value: app-canary
      # Need to change these so that the deployment can link to its pods correctly
      # https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#selector
      - op: replace
        path: /metadata/labels/track
        value: canary
      - op: replace
        path: /spec/selector/matchLabels/track
        value: canary
      - op: replace
        path: /spec/template/metadata/labels/track
        value: canary
    target:
      kind: Deployment
      name: app